### ISSUE TITLE
Ocean monument does not generate at ground level

### ISSUE THREAD

**Issue by Eatham532** [YUNG-GANG/YUNGs-Better-Ocean-Monuments#2]
![2022-10-04_21 54 24](https://user-images.githubusercontent.com/78714349/193946266-14d455c6-3a1d-4a80-8189-5dcbfe1e94fa.png)

V 1.19.2, V2.0 Fabric

It feels like the ocean monument is in a hole in the ground. 
Maybe if this happens you fill the air blocks with stone. Or just change the level of the ground.

**Comment by yungnickyoung** [comment]
This is intended, as otherwise they would protrude way too much from the surface.

**Comment by ParasiticSquid** [comment]
I noticed it's much less noticeable if they generate in deep ocean type biomes, otherwise they do the hole thing in a normal ocean. Way you can "fix" it is set them to only generate in deep oceans I suppose since they have a lower surface on the ocean floor then a normal ocean giving the monuments more leeway to not look derpy compared to the surroundings
